- hosts: web
  become: yes
  tasks:
    - name: "update"
        apt: 
          update_cache: yes
          cache_valid_time: 3600
    - name: "install nodeJS and some packages"
      apt:
        install npm
    - name: "npm packages"
      shell:
        npm init -y
        npm i express nodemailer
        npm i -D nodemon